# Generated by Django 5.2.6 on 2025-09-09 01:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='Dafra Cruisym 300', max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(default='Dafra', max_length=50, verbose_name='Marca')),
                ('ano', models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor')),
                ('km_atual', models.PositiveIntegerField(default=0, verbose_name='Km Atual')),
                ('km_compra', models.PositiveIntegerField(default=0, verbose_name='Km na Compra')),
                ('cilindrada', models.PositiveIntegerField(default=300, verbose_name='Cilindrada (cc)')),
                ('tipo_motor', models.CharField(default='4 tempos', max_length=50, verbose_name='Tipo de Motor')),
                ('tipo_transmissao', models.CharField(default='Manual', max_length=50, verbose_name='Transmissão')),
                ('tipo_combustivel', models.CharField(default='Gasolina', max_length=20, verbose_name='Combustível')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa')),
                ('chassi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chassi')),
                ('renavam', models.CharField(blank=True, max_length=20, null=True, verbose_name='Renavam')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='Data da Compra')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='motos/', verbose_name='Imagem Principal')),
                ('documento_compra', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Documento de Compra')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motos_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_condutor', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, verbose_name='Peso do Condutor (kg)')),
                ('altura_condutor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura do Condutor (cm)')),
                ('capacidade_carga', models.DecimalField(decimal_places=2, default=180.0, max_digits=5, verbose_name='Capacidade de Carga (kg)')),
                ('tipo_pneu', models.CharField(choices=[('urbano', 'Urbano'), ('misto', 'Misto'), ('off_road', 'Off-Road')], default='urbano', max_length=20, verbose_name='Tipo de Pneu')),
                ('tamanho_aro_dianteira', models.CharField(default='17"', max_length=10, verbose_name='Aro Dianteiro')),
                ('tamanho_aro_traseira', models.CharField(default='17"', max_length=10, verbose_name='Aro Traseiro')),
                ('estilo_uso', models.CharField(choices=[('urbano', 'Urbano'), ('estrada', 'Estrada'), ('off_road', 'Off-Road'), ('esportivo', 'Esportivo')], default='urbano', max_length=20, verbose_name='Estilo de Uso')),
                ('frequencia_uso', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], default='diario', max_length=20, verbose_name='Frequência de Uso')),
                ('distancia_media_dia', models.DecimalField(decimal_places=2, default=25.0, max_digits=6, verbose_name='Distância Média/Dia (km)')),
                ('velocidade_media', models.DecimalField(decimal_places=2, default=35.0, max_digits=5, verbose_name='Velocidade Média (km/h)')),
                ('tipo_via_predominante', models.CharField(choices=[('cidade', 'Cidade'), ('estrada', 'Estrada'), ('misto', 'Misto')], default='cidade', max_length=20, verbose_name='Tipo de Via Predominante')),
                ('condicoes_via', models.CharField(choices=[('excelente', 'Excelente'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='regular', max_length=20, verbose_name='Condições da Via')),
                ('clima_predominante', models.CharField(choices=[('seco', 'Seco'), ('umido', 'Úmido'), ('quente', 'Quente'), ('frio', 'Frio')], default='seco', max_length=20, verbose_name='Clima Predominante')),
                ('calibragem_recomendada_dianteira', models.DecimalField(decimal_places=2, default=2.2, max_digits=4, verbose_name='Calibragem Recomendada Dianteira (PSI)')),
                ('calibragem_recomendada_traseira', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Calibragem Recomendada Traseira (PSI)')),
                ('calibragem_atual_dianteira', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Calibragem Atual Dianteira (PSI)')),
                ('calibragem_atual_traseira', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Calibragem Atual Traseira (PSI)')),
                ('ultima_calibragem', models.DateField(blank=True, null=True, verbose_name='Última Calibragem')),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Imagem do Perfil')),
                ('documento_perfil', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Documento do Perfil')),
                ('observacoes_perfil', models.TextField(blank=True, null=True, verbose_name='Observações do Perfil')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('moto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Perfil da Moto',
                'verbose_name_plural': 'Perfis das Motos',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rota', models.CharField(max_length=100, verbose_name='Nome da Rota')),
                ('tipo_via', models.CharField(choices=[('cidade', 'Cidade'), ('estrada', 'Estrada'), ('misto', 'Misto')], default='cidade', max_length=20, verbose_name='Tipo de Via')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Distância (km)')),
                ('tempo_estimado', models.DurationField(blank=True, null=True, verbose_name='Tempo Estimado')),
                ('velocidade_media', models.DecimalField(decimal_places=2, default=35.0, max_digits=5, verbose_name='Velocidade Média (km/h)')),
                ('condicoes_via', models.CharField(choices=[('excelente', 'Excelente'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='regular', max_length=20, verbose_name='Condições da Via')),
                ('clima', models.CharField(choices=[('seco', 'Seco'), ('umido', 'Úmido'), ('quente', 'Quente'), ('frio', 'Frio')], default='seco', max_length=20, verbose_name='Clima')),
                ('frequencia_semanal', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Frequência Semanal')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-data_registro'],
                'unique_together': {('moto', 'nome_rota')},
            },
        ),
    ]
