# Generated by Django 5.2.6 on 2025-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='marca',
            field=models.CharField(choices=[('Bajaj', 'Bajaj'), ('BMW', 'BMW'), ('Dafra', 'Dafra'), ('Ducati', 'Ducati'), ('Harley-Davidson', 'Harley-Davidson'), ('Honda', 'Honda'), ('Husqvarna', 'Husqvarna'), ('Kawasaki', 'Kawasaki'), ('KTM', 'KTM'), ('Royal Enfield', 'Royal Enfield'), ('Shineray', 'Shineray'), ('Suzuki', 'Suzuki'), ('Triumph', 'Triumph'), ('Yamaha', 'Yamaha'), ('Outras', 'Outras')], default='Dafra', max_length=50, verbose_name='Marca'),
        ),
    ]
