# Generated by Django 5.2.6 on 2025-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_alter_moto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='cor',
            field=models.CharField(blank=True, choices=[('Preto', 'Preto'), ('Branco', 'Branco'), ('Prata', 'Prata'), ('Azul', 'Azul'), ('Vermelho', 'Vermelho'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Laranja', 'Laranja'), ('Cinza', 'Cinza'), ('Dourado', 'Dourado'), ('Roxo', 'Roxo'), ('Rosa', 'Rosa'), ('Outras', 'Outras')], max_length=50, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='tipo_combustivel',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Etanol', 'Etanol'), ('Flex', 'Flex (Gasolina/Etanol)'), ('Elétrico', 'Elétrico'), ('Diesel', 'Diesel')], default='Gasolina', max_length=20, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='tipo_motor',
            field=models.CharField(choices=[('2 tempos', '2 Tempos'), ('4 tempos', '4 Tempos'), ('Elétrico', 'Elétrico')], default='4 tempos', max_length=50, verbose_name='Tipo de Motor'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='tipo_transmissao',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automática', 'Automática'), ('CVT', 'CVT (Variação Contínua)'), ('Semi-automática', 'Semi-automática')], default='Manual', max_length=50, verbose_name='Transmissão'),
        ),
    ]
