# Generated by Django 5.2.6 on 2025-09-09 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0003_alter_moto_cor_alter_moto_tipo_combustivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='ano',
        ),
        migrations.AddField(
            model_name='moto',
            name='ano_fim',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano Fim'),
        ),
        migrations.AddField(
            model_name='moto',
            name='ano_inicio',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano Início'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cilindrada',
            field=models.PositiveIntegerField(choices=[(50, '50cc'), (100, '100cc'), (110, '110cc'), (125, '125cc'), (150, '150cc'), (160, '160cc'), (200, '200cc'), (250, '250cc'), (300, '300cc'), (400, '400cc'), (500, '500cc'), (600, '600cc'), (650, '650cc'), (750, '750cc'), (800, '800cc'), (900, '900cc'), (1000, '1000cc'), (1200, '1200cc'), (1300, '1300cc'), (1500, '1500cc'), (1800, '1800cc')], default=300, verbose_name='Cilindrada (cc)'),
        ),
    ]
