# Generated by Django 5.2.6 on 2025-09-09 01:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('marca_recomendada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca Recomendada')),
                ('modelo_recomendada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Recomendado')),
                ('quantidade_padrao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Quantidade Padrão')),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade de Medida')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Item de Manutenção',
                'verbose_name_plural': 'Itens de Manutenção',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('melhoria', 'Melhoria')], max_length=50, verbose_name='Categoria')),
                ('intervalo_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalo (km)')),
                ('intervalo_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalo (meses)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Manutenção',
                'verbose_name_plural': 'Tipos de Manutenção',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('comprada', 'Itens Comprados'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('km_atual', models.PositiveIntegerField(verbose_name='Km Atual na Manutenção')),
                ('km_proxima', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km para Próxima Manutenção')),
                ('data_planejada', models.DateField(blank=True, null=True, verbose_name='Data Planejada')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('local_manutencao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local da Manutenção')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado (R$)')),
                ('valor_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Real (R$)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='motos.moto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='manutencoes.tipomanutencao')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_planejada', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemManutencaoRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade Utilizada')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('marca_utilizada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca Utilizada')),
                ('modelo_utilizado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Utilizado')),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='Nota Fiscal')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizacoes', to='manutencoes.itemmanutencao')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_utilizados', to='manutencoes.manutencao')),
            ],
            options={
                'verbose_name': 'Item Utilizado',
                'verbose_name_plural': 'Itens Utilizados',
                'ordering': ['item__nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.TextField(blank=True, null=True, verbose_name='Sintomas Relatados')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('procedimentos_realizados', models.TextField(blank=True, null=True, verbose_name='Procedimentos Realizados')),
                ('satisfacao', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Satisfação (1-5)')),
                ('recomendacao', models.TextField(blank=True, null=True, verbose_name='Recomendação')),
                ('fotos_antes', models.ImageField(blank=True, null=True, upload_to='manutencao/fotos_antes/', verbose_name='Fotos Antes')),
                ('fotos_depois', models.ImageField(blank=True, null=True, upload_to='manutencao/fotos_depois/', verbose_name='Fotos Depois')),
                ('relatorio_tecnico', models.FileField(blank=True, null=True, upload_to='manutencao/relatorios/', verbose_name='Relatório Técnico')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('manutencao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='manutencoes.manutencao')),
            ],
            options={
                'verbose_name': 'Histórico de Manutenção',
                'verbose_name_plural': 'Históricos de Manutenção',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='itemmanutencao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='manutencoes.tipomanutencao'),
        ),
        migrations.AlterUniqueTogether(
            name='itemmanutencao',
            unique_together={('tipo', 'nome')},
        ),
    ]
