# Generated by Django 5.2.6 on 2025-09-09 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('financeiro', 'Financeiro'), ('manutencao', 'Manutenção'), ('desempenho', 'Desempenho'), ('seguranca', 'Segurança'), ('consumo', 'Consumo')], max_length=20, verbose_name='Tipo')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('unidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manutencao', 'Manutenção'), ('seguranca', 'Segurança'), ('desempenho', 'Desempenho'), ('financeiro', 'Financeiro'), ('sistema', 'Sistema')], max_length=20, verbose_name='Tipo')),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Severidade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('lido', 'Lido'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='ativo', max_length=20, verbose_name='Status')),
                ('acao_recomendada', models.TextField(blank=True, null=True, verbose_name='Ação Recomendada')),
                ('link_acao', models.URLField(blank=True, null=True, verbose_name='Link para Ação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lido_em', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('intervalo_recorrencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalo de Recorrência (dias)')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='motos.moto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-severidade', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metricas_favoritas', models.JSONField(blank=True, null=True, verbose_name='Métricas Favoritas')),
                ('widgets_visiveis', models.JSONField(blank=True, null=True, verbose_name='Widgets Visíveis')),
                ('periodo_padrao', models.CharField(choices=[('7d', '7 dias'), ('30d', '30 dias'), ('90d', '90 dias'), ('1y', '1 ano')], default='30d', max_length=20, verbose_name='Período Padrão')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro'), ('auto', 'Automático')], default='auto', max_length=20, verbose_name='Tema')),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('lista', 'Lista'), ('compacto', 'Compacto')], default='grid', max_length=20, verbose_name='Layout')),
                ('notificacoes_ativas', models.BooleanField(default=True, verbose_name='Notificações Ativas')),
                ('email_alertas', models.BooleanField(default=False, verbose_name='Alertas por Email')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('moto_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_principal', to='motos.moto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manutencao', 'Manutenção'), ('financeiro', 'Financeiro'), ('desempenho', 'Desempenho'), ('analise', 'Análise'), ('completo', 'Completo')], max_length=20, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('filtros', models.JSONField(blank=True, null=True, verbose_name='Filtros Aplicados')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='relatorios/', verbose_name='Arquivo PDF')),
                ('arquivo_excel', models.FileField(blank=True, null=True, upload_to='relatorios/', verbose_name='Arquivo Excel')),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='gerando', max_length=20, verbose_name='Status')),
                ('total_registros', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Registros')),
                ('tempo_geracao', models.DurationField(blank=True, null=True, verbose_name='Tempo de Geração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ValorMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor')),
                ('valor_texto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Texto')),
                ('data_referencia', models.DateField(verbose_name='Data de Referência')),
                ('periodo', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Período')),
                ('contexto', models.JSONField(blank=True, null=True, verbose_name='Contexto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='dashboard.metrica')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Valor de Métrica',
                'verbose_name_plural': 'Valores de Métricas',
                'ordering': ['-data_referencia', '-criado_em'],
                'unique_together': {('metrica', 'moto', 'data_referencia', 'periodo')},
            },
        ),
    ]
